export const form = {
  id: 'c6flqC4da3_C',
  title: 'EQ-5D-5L',
  questions: [
    {
      id: 'dV6Qua7n0DLe',
      title:
        'Please select the ONE box that best describes your health TODAY.\n\nMobility',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'DXpgo17w7pBY',
          value: 1,
          label: 'I have no problems in walking about',
          __typename: 'Option',
        },
        {
          id: 'FovjgtFLVEqB',
          value: 2,
          label: 'I have slight problems in walking about',
          __typename: 'Option',
        },
        {
          id: 'RZlwo50mnO5G',
          value: 3,
          label: 'I have moderate problems in walking about',
          __typename: 'Option',
        },
        {
          id: 'wel27DhYWsUI',
          value: 4,
          label: 'I have severe problems in walking about',
          __typename: 'Option',
        },
        {
          id: 'kgFRoX9eNlBX',
          value: 5,
          label: 'I am unable to walk about',
          __typename: 'Option',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        use_select: null,
        slider: null,
        __typename: 'QuestionConfig',
      },
      __typename: 'Question',
    },
    {
      id: 'Oq7mZGtDbN3m',
      title:
        'Please select the ONE box that best describes your health TODAY.\n\nSelf-care',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'OGaN8vlpOqVD',
          value: 1,
          label: 'I have no problems washing or dressing myself',
          __typename: 'Option',
        },
        {
          id: '9Yi0-vDajHka',
          value: 2,
          label: 'I have slight problems washing or dressing myself',
          __typename: 'Option',
        },
        {
          id: 'lpFQkbwXjSa1',
          value: 3,
          label: 'I have moderate problems washing or dressing myself',
          __typename: 'Option',
        },
        {
          id: 'TXrPCmBXJW2r',
          value: 4,
          label: 'I have severe problems washing or dressing myself',
          __typename: 'Option',
        },
        {
          id: '1PnHsfib5yxj',
          value: 5,
          label: 'I am unable to wash or dress myself',
          __typename: 'Option',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        use_select: null,
        slider: null,
        __typename: 'QuestionConfig',
      },
      __typename: 'Question',
    },
    {
      id: '9SqhWw14X_9b',
      title:
        'Please select the ONE box that best describes your health TODAY.\n\nUsual activities (e.g. work, study, housework, family or leisure activities)',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'KPJTUXOcLaXo',
          value: 1,
          label: 'I have no problems doing my usual activities',
          __typename: 'Option',
        },
        {
          id: 's7gi89ObI_Mo',
          value: 2,
          label: 'I have slight problems doing my usual activities',
          __typename: 'Option',
        },
        {
          id: 'o5PmMExPU4Vq',
          value: 3,
          label: 'I have moderate problems doing my usual activities',
          __typename: 'Option',
        },
        {
          id: 'ZgqAg98XJyNC',
          value: 4,
          label: 'I have severe problems doing my usual activities',
          __typename: 'Option',
        },
        {
          id: 'oiKk5GLvgBC0',
          value: 5,
          label: 'I am unable to do my usual activities',
          __typename: 'Option',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        use_select: null,
        slider: null,
        __typename: 'QuestionConfig',
      },
      __typename: 'Question',
    },
    {
      id: 'VjxlEATqpQzc',
      title:
        'Please select the ONE box that best describes your health TODAY.\n\nPain/discomfort',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'Yk5ipCX4LnJi',
          value: 1,
          label: 'I have no pain or discomfort',
          __typename: 'Option',
        },
        {
          id: 'JpuDba0mC-z2',
          value: 2,
          label: 'I have slight pain or discomfort',
          __typename: 'Option',
        },
        {
          id: 'f5yurl6lyFMD',
          value: 3,
          label: 'I have moderate pain or discomfort',
          __typename: 'Option',
        },
        {
          id: 'sP_B0K5K4vuB',
          value: 4,
          label: 'I have severe pain or discomfort',
          __typename: 'Option',
        },
        {
          id: 'A4AVwAoIdsD1',
          value: 5,
          label: 'I have extreme pain or discomfort',
          __typename: 'Option',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        use_select: null,
        slider: null,
        __typename: 'QuestionConfig',
      },
      __typename: 'Question',
    },
    {
      id: 'Lb7hcB7Wm3RT',
      title:
        'Please select the ONE box that best describes your health TODAY.\n\nAnxiety/depression',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'P3taqrFTJ4cn',
          value: 1,
          label: 'I am not anxious or depressed',
          __typename: 'Option',
        },
        {
          id: 'sJGyJBW6sHVp',
          value: 2,
          label: 'I am slightly anxious or depressed',
          __typename: 'Option',
        },
        {
          id: '-3hDxxRfx7m_',
          value: 3,
          label: 'I am moderately anxious or depressed',
          __typename: 'Option',
        },
        {
          id: 'Ut0GHfjMjKCh',
          value: 4,
          label: 'I am severely anxious or depressed',
          __typename: 'Option',
        },
        {
          id: 'wWGBBTztuyo5',
          value: 5,
          label: 'I am extremely anxious or depressed',
          __typename: 'Option',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        use_select: null,
        slider: null,
        __typename: 'QuestionConfig',
      },
      __typename: 'Question',
    },
    {
      id: 'L3-VhVUwjN-Z',
      title:
        '- We would like to know how good or bad your health is TODAY. \n- This scale is numbered from 0 to 100. \n- 100 means the best health you can imagine. 0 means the worst health you can imagine.\n- Indicate on the scale how your health is TODAY.\n',
      dataPointValueType: 'NUMBER',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'SLIDER',
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        use_select: null,
        slider: {
          min: 0,
          max: 100,
          step_value: 1,
          display_marks: true,
          min_label: 'The worst health you can imagine',
          max_label: 'The best health you can imagine',
          is_value_tooltip_on: true,
          show_min_max_values: true,
          __typename: 'SliderConfig',
        },
        __typename: 'QuestionConfig',
      },
      __typename: 'Question',
    },
  ],
}
