import { Form } from '../../../../types'
import {
  DataPointValueType,
  QuestionType,
  UserQuestionType,
} from '../../../../types/question'

export const form: Form = {
  id: 'Kzr2NafTxJfR',
  title: 'Example form',
  key: 'exampleForm',
  definition_id: '',
  release_id: '',
  questions: [
    {
      id: 'x5bgJqsOltmK3',
      title: 'Single select question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'singleSelectQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [
        {
          id: 'q01_1',
          label: 'Option 1',
          value: 0,
          value_string: '0',
        },
        {
          id: 'q01_2',
          label: 'Option 2',
          value: 1,
          value_string: '1',
        },
        {
          id: 'q01_3',
          label: 'Option 3',
          value: 3,
          value_string: '3',
        },
        {
          id: 'q01_4',
          label: 'Option 4',
          value: 4,
          value_string: '4',
        },
        {
          id: 'q01_5',
          label: 'Option 5',
          value: 5,
          value_string: '5',
        },
      ],
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleChoice,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'x5bgJqOltmK3',
      title: 'Single select question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'singleSelectQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [
        {
          id: 'q02_1',
          label: 'Option 1',
          value: 0,
          value_string: '0',
        },
        {
          id: 'q02_2',
          label: 'Option 2',
          value: 1,
          value_string: '1',
        },
        {
          id: 'q02_3',
          label: 'Option 3',
          value: 3,
          value_string: '3',
        },
        {
          id: 'q02_4',
          label: 'Option 4',
          value: 4,
          value_string: '4',
        },
        {
          id: 'q02_5',
          label: 'Option 5',
          value: 5,
          value_string: '5',
        },
      ],
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleChoice,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
    {
      id: 'HyIaUkgDcXwR',
      title: 'This is multiple select question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsMultipleSelectQuestion',
      dataPointValueType: DataPointValueType.NumbersArray,
      options: [
        {
          id: 'q3_ZT6yN64opulL',
          value: 0,
          label: 'Option 1',
          value_string: '0',
        },
        {
          id: 'q3_RqYicEXp0agy',
          value: 1,
          label: 'Option 2',
          value_string: '1',
        },
        {
          id: 'q3_d_uA9ldC6L8_',
          value: 2,
          label: 'Option 3',
          value_string: '2',
        },
        {
          id: 'q3_ZkhlOC3DfSOF',
          value: 3,
          label: 'Option 4',
          value_string: '3',
        },
      ],
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleSelect,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'VkL1vrscT5sdMV',
      title: 'This is date question',
      definition_id: 'Kzar2NafTxJfR',
      key: 'thisIsDateQuestion',
      dataPointValueType: DataPointValueType.Date,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Date,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'VkL1vrscT5MV',
      title: 'This is yes or no question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsYesOrNoQuestion',
      dataPointValueType: DataPointValueType.Boolean,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.YesNo,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
    {
      id: 'VkL1vrscT5MV',
      title: 'This is phone number question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsPhoneNumberQuestion',
      dataPointValueType: DataPointValueType.Telephone,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Telephone,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
    {
      id: 'fSN5BktQ6cOV',
      title:
        '[{"type":"p","children":[{"text":"This ","bold":true},{"text":"is","italic":true},{"text":" "},{"text":"rich text","strikethrough":true},{"text":" "},{"text":"description","underline":true}]}]',
      definition_id: 'Kzr2NafTxJfR',
      key: 'typePChildrenTextThisBoldTrueTextIsItalicTrueTextTextRichTextStrikethroughTrueTextTextDescriptionUnderlineTrue',
      dataPointValueType: null,
      options: [],
      questionType: QuestionType.NoInput,
      userQuestionType: UserQuestionType.Description,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'XAgYxu_kbDPj',
      title: 'This is slider question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsSliderQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Slider,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: {
          min: 0,
          max: 10,
          step_value: 1,
          display_marks: true,
          min_label: 'Min',
          max_label: 'Max',
          is_value_tooltip_on: true,
          show_min_max_values: true,
        },
      },
    },
    {
      id: '5KMcDYtoz0rr',
      title: 'This is number question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsNumberQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Number,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'U99uUQ_Jp5Jb',
      title: 'This is short text question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsShortTextQuestion',
      dataPointValueType: DataPointValueType.String,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.ShortText,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: '6mv3n9HaXFTU',
      title: 'This is long text question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsLongTextQuestion',
      dataPointValueType: DataPointValueType.String,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.LongText,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'HyIaUksdgDcXwR',
      title: 'This is a phone number question',
      definition_id: 'Kzr2NafsaaTxJfR',
      key: 'thisIsPhoneNumberQuestion',
      dataPointValueType: DataPointValueType.Telephone,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Telephone,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'HyIaUasadkgDcXwR',
      title: 'This is multiple select question - with Select input',
      definition_id: 'Kzr2NafsaaTxJfR',
      key: 'thisIsMultipleSelectQuestionWithSelectInput',
      dataPointValueType: DataPointValueType.NumbersArray,
      options: [
        {
          id: 'q10_ZT6yN64opulL',
          value: 0,
          label: 'Option 1',
          value_string: '0',
        },
        {
          id: 'q10_RqYicEXp0agy',
          value: 1,
          label: 'Option 2',
          value_string: '1',
        },
        {
          id: 'q10_d_uA9ldC6L8_',
          value: 2,
          label: 'Option 3',
          value_string: '2',
        },
        {
          id: 'q10_ZkhlOC3DfSOF',
          value: 3,
          label: 'Option 4',
          value_string: '3',
        },
      ],
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleSelect,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
        use_select: true,
      },
    },
    {
      id: 'HyIaUkgDczxXwR',
      title: 'This is multiple choice question - with Select input',
      definition_id: 'Kzr2NasfTxJfR',
      key: 'thisIsMultipleChoiceQuestionWithSelectInput',
      dataPointValueType: DataPointValueType.Number,
      options: [
        {
          id: 'q11_ZT6yN64opulL',
          value: 0,
          label: 'Option 1',
          value_string: '0',
        },
        {
          id: 'q11_RqYicEXp0agy',
          value: 1,
          label: 'Option 2',
          value_string: '1',
        },
        {
          id: 'q11_d_uA9ldC6L8_',
          value: 2,
          label: 'Option 3',
          value_string: '2',
        },
        {
          id: 'q11_ZkhlOC3DfSOF',
          value: 3,
          label: 'Option 4',
          value_string: '3',
        },
      ],
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleChoice,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
        use_select: true,
      },
    },
  ],
}

export const formWithTwoRequiredSingleSelectQuestions: Form = {
  id: 'Kzr2NafTxJfR',
  title: 'Example form',
  key: 'exampleForm',
  definition_id: '',
  release_id: '',
  questions: [
    {
      id: 'x5bgJqOltmK3',
      title: 'Single select question #1',
      definition_id: 'Kzr2NafTxJfR',
      key: 'singleSelectQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [
        {
          id: 'q1_1',
          label: 'Answer the first required question',
          value: 0,
          value_string: '0',
        },
        {
          id: 'q1_2',
          label: 'Option 2',
          value: 1,
          value_string: '1',
        },
      ],
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleChoice,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
    {
      id: 'x5bgJqOltmK3',
      title: 'Single select question #2',
      definition_id: 'Kzr2NafTxJfR',
      key: 'singleSelectQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [
        {
          id: 'q2_1',
          label: 'Option 1',
          value: 0,
          value_string: '0',
        },
        {
          id: 'q2_2',
          label: 'Option 2',
          value: 1,
          value_string: '1',
        },
      ],
      questionType: QuestionType.MultipleChoice,
      userQuestionType: UserQuestionType.MultipleChoice,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
  ],
}

export const sliderQuestionForm: Form = {
  id: 'Tzr2NafTxJfR',
  title: 'Form with slider question',
  key: 'formWithSliderQuestion',
  definition_id: '',
  release_id: '',
  questions: [
    {
      id: 'XAgYxu_kbDPj',
      title: 'This is slider question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsSliderQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Slider,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: {
          min: 0,
          max: 10,
          step_value: 1,
          display_marks: false,
          min_label: '',
          max_label: '',
          is_value_tooltip_on: false,
          show_min_max_values: false,
        },
      },
    },
    {
      id: '5KMcDYtoz0rr',
      title: 'This is number question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsNumberQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Number,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
  ],
}

export const dateQuestionForm: Form = {
  id: 'Tzr2NafTxJfR',
  title: 'Form with date question',
  key: 'formWithDateQuestion',
  definition_id: '',
  release_id: '',
  questions: [
    {
      id: 'XAgYxu_kbDPj',
      title: 'This is date question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsDateQuestion',
      dataPointValueType: DataPointValueType.Date,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Date,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
      },
    },
    {
      id: '5KMcDYtoz0rr',
      title: 'This is number question',
      definition_id: 'Kzr2NafTxJfR',
      key: 'thisIsNumberQuestion',
      dataPointValueType: DataPointValueType.Number,
      options: [],
      questionType: QuestionType.Input,
      userQuestionType: UserQuestionType.Number,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
  ],
}
