import { Form } from '../types'

export const form: Form = {
  id: 'Kzr2NafTxJfR',
  title: 'Example form',
  key: 'exampleForm',
  questions: [
    {
      id: 'fSN5BktQ6cOV',
      title:
        '[{"type":"p","children":[{"text":"This ","bold":true},{"text":"is","italic":true},{"text":" "},{"text":"rich text","strikethrough":true},{"text":" "},{"text":"description","underline":true}]}]',
      form_id: 'Kzr2NafTxJfR',
      key: 'typePChildrenTextThisBoldTrueTextIsItalicTrueTextTextRichTextStrikethroughTrueTextTextDescriptionUnderlineTrue',
      dataPointValueType: null,
      options: [],
      questionType: 'NO_INPUT',
      userQuestionType: 'DESCRIPTION',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'x5bgJqOltmK3',
      title: 'Single select question',
      form_id: 'Kzr2NafTxJfR',
      key: 'singleSelectQuestion',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'IsunqUEdINiG',
          value: 0,
          label: 'Option 1',
        },
        {
          id: 'ReyaXYJpKwNy',
          value: 1,
          label: 'Option 2',
        },
        {
          id: 'mNgpZbOF-z78',
          value: 2,
          label: 'Option 3',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'HyIaUkgDcXwR',
      title: 'This is multiple select question',
      form_id: 'Kzr2NafTxJfR',
      key: 'thisIsMultipleSelectQuestion',
      dataPointValueType: 'NUMBERS_ARRAY',
      options: [
        {
          id: 'ZT6yN64opulL',
          value: 0,
          label: 'Option 1',
        },
        {
          id: 'RqYicEXp0agy',
          value: 1,
          label: 'Option 2',
        },
        {
          id: 'd_uA9ldC6L8_',
          value: 2,
          label: 'Option 3',
        },
        {
          id: 'ZkhlOC3DfSOF',
          value: 3,
          label: 'Option 4',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_SELECT',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'VkL1vrscT5MV',
      title: 'This is yes or no question',
      form_id: 'Kzr2NafTxJfR',
      key: 'thisIsYesOrNoQuestion',
      dataPointValueType: 'BOOLEAN',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'YES_NO',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'XAgYxu_kbDPj',
      title: 'This is slider question',
      form_id: 'Kzr2NafTxJfR',
      key: 'thisIsSliderQuestion',
      dataPointValueType: 'NUMBER',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'SLIDER',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: {
          min: 0,
          max: 10,
          step_value: 1,
          display_marks: false,
          min_label: '',
          max_label: '',
          is_value_tooltip_on: false,
          show_min_max_values: false,
        },
      },
    },
    {
      id: '5KMcDYtoz0rr',
      title: 'This is number question',
      form_id: 'Kzr2NafTxJfR',
      key: 'thisIsNumberQuestion',
      dataPointValueType: 'NUMBER',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'NUMBER',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'U99uUQ_Jp5Jb',
      title: 'This is short text question',
      form_id: 'Kzr2NafTxJfR',
      key: 'thisIsShortTextQuestion',
      dataPointValueType: 'STRING',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'SHORT_TEXT',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: '6mv3n9HaXFTU',
      title: 'This is long text question',
      form_id: 'Kzr2NafTxJfR',
      key: 'thisIsLongTextQuestion',
      dataPointValueType: 'STRING',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'LONG_TEXT',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
  ],
}
