import { Form } from '../types'

export const form: Form = {
  id: 'cOhOlztRmi-M',
  title: 'New form short',
  key: 'newFormShort',
  questions: [
    {
      id: 'F9wnzORlsXcZ',
      title: 'birth date',
      form_id: 'cOhOlztRmi-M',
      key: 'birthDate',
      dataPointValueType: 'DATE',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'DATE',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'TCvRyRL9j1qc',
      title: 'how are u',
      form_id: 'cOhOlztRmi-M',
      key: 'howAreU',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'AF4MWSALx0ar',
          value: 0,
          label: 'good',
        },
        {
          id: 'WboVJ14_kCQe',
          value: 1,
          label: 'bad',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      rule_id: '1eyzl9UaSVNI',
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
    {
      id: 'TCvRyRL9j1qc',
      title: 'Question lorem ipsum',
      form_id: 'cOhOlztRmi-M',
      key: 'questionLoremIpsum',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'badA-WhBbGv4',
          value: 0,
          label: 'yes',
        },
        {
          id: '8M9ZFV6dYLrG',
          value: 1,
          label: 'no',
        },
        {
          id: 'iNAdQtvEPpO8',
          value: 2,
          label: 'maybe',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: '0hAZVjrYS4-d',
      title: 'How tired are u',
      form_id: 'cOhOlztRmi-M',
      key: 'howTiredAreU',
      dataPointValueType: 'NUMBER',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'SLIDER',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: {
          min: 0,
          max: 10,
          step_value: 1,
          display_marks: false,
          min_label: '1',
          max_label: '10',
          is_value_tooltip_on: false,
          show_min_max_values: false,
        },
      },
    },
    {
      id: 'xKs-m7Jqwfps',
      title: 'Do you like dogs',
      form_id: 'cOhOlztRmi-M',
      key: 'doYouLikeDogs',
      dataPointValueType: 'BOOLEAN',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'YES_NO',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
    {
      id: 'xKs-m7Jqwfpd',
      title: 'lorem ipsum',
      form_id: 'cOhOlztRmi-M',
      key: 'loremIpsum',
      dataPointValueType: 'NUMBER',
      options: [
        {
          id: 'OkyD4DqalFfk',
          value: 0,
          label: 'dolor sit amed',
        },
        {
          id: 'tTJxzAXa2Zij',
          value: 1,
          label: 'no idea',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_CHOICE',
      rule_id: 'lZ-mYmcbgNaB',
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'XU4RgeoA-wZS',
      title: 'Write a long text here',
      form_id: 'cOhOlztRmi-M',
      key: 'writeALongTextHere',
      dataPointValueType: 'STRING',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'LONG_TEXT',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
    {
      id: 'dXAN7MeyGXbA',
      title: 'Multiple select question',
      form_id: 'cOhOlztRmi-M',
      key: 'multipleSelectQuestion',
      dataPointValueType: 'NUMBERS_ARRAY',
      options: [
        {
          id: 'gsdzKdxul5B3',
          value: 0,
          label: 'option 1',
        },
        {
          id: 'JFb6DaMrSrRp',
          value: 1,
          label: 'option 2',
        },
        {
          id: '-z-6bG4y2R3T',
          value: 2,
          label: 'option 3',
        },
      ],
      questionType: 'MULTIPLE_CHOICE',
      userQuestionType: 'MULTIPLE_SELECT',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'EUox8_vOZatU',
      title: 'How old are you',
      form_id: 'cOhOlztRmi-M',
      key: 'howOldAreYou',
      dataPointValueType: 'NUMBER',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'NUMBER',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: true,
        slider: null,
      },
    },
    {
      id: '6GOSGHcQz_eZ',
      title: 'Name',
      form_id: 'cOhOlztRmi-M',
      key: 'name',
      dataPointValueType: 'STRING',
      options: [],
      questionType: 'INPUT',
      userQuestionType: 'SHORT_TEXT',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
    {
      id: 'k4UpWCmip5qf',
      title:
        '[{"type":"p","children":[{"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "},{"text":"Ut enim ad minim veniam,","bold":true},{"text":" quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."}]},{"type":"h1","children":[{"text":" Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"}]},{"type":"p","children":[{"text":""}]}]',
      form_id: 'cOhOlztRmi-M',
      key: 'typePChildrenTextLoremIpsumDolorSitAmetConsecteturAdipiscingElitSedDoEiusmodTemporIncididuntUtLaboreEtDoloreMagnaAliquaTextUtEnimAdMinimVeniamBoldTrueTextQuisNostrudExercitationUllamcoLaborisNisiUtAliquipExEaCommodoConsequatTypeH1ChildrenTextDuisAuteIrureDolorInReprehenderitInVoluptateVelitEsseCillumDoloreEuFugiatNullaPariaturExcepteurSintOccaecatCupidatatNonProidentSuntInCulpaQuiOfficiaDeseruntMollitAnimIdEstLaborumTypePChildrenText',
      dataPointValueType: null,
      options: [],
      questionType: 'NO_INPUT',
      userQuestionType: 'DESCRIPTION',
      rule_id: null,
      questionConfig: {
        recode_enabled: false,
        mandatory: false,
        slider: null,
      },
    },
  ],
}
